language: rust
sudo: required # so we get a VM with higher specs
dist: trusty # so we get a VM with higher specs
os:
  - linux
  - windows
env:
  - TEST_FLAGS=
  - TEST_FLAGS=--release
  - TEST_FLAGS=--contrib
rust:
  - nightly
script: ./scripts/test.sh $TEST_FLAGS
